version: '3.7'

services:
  mailer:
    container_name: mailer
    image: mailer_image
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8002:8002"
    depends_on: [mailhog]
    networks:
      - network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - network

networks:
  network:
    driver: bridge